<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9d5c58b-a9ce-49de-a450-5fbeae9896ab</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MailKit" Version="4.9.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MongoDB.Bson" Version="2.28.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HUBT_Social_Base">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_Identity_Service\bin\Debug\net8.0\HUBT_Social_Base.dll</HintPath>
    </Reference>
    <Reference Include="HUBT_Social_Core">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_MongoDb_Service\bin\Debug\net8.0\HUBT_Social_Core.dll</HintPath>
    </Reference>
    <Reference Include="HUBT_Social_Email_Service">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_Email_Service\bin\Debug\net8.0\HUBT_Social_Email_Service.dll</HintPath>
    </Reference>
    <Reference Include="HUBT_Social_MongoDb_Service">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_MongoDb_Service\bin\Debug\net8.0\HUBT_Social_MongoDb_Service.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
