<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>59a9d4d7-4d1a-41f2-8e44-0414f9b35788</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HUBT_Social_Base">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_MongoDb_Service\bin\Debug\net8.0\HUBT_Social_Base.dll</HintPath>
    </Reference>
    <Reference Include="HUBT_Social_Core">
      <HintPath>..\..\HUBT_Social_Core\HUBT_Social_MongoDb_Service\bin\Debug\net8.0\HUBT_Social_Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
